name:                 extensible-exceptions
version:              0.1.1.4
visibility:           public
id:                   extensible-exceptions-0.1.1.4-6aNRrQW8livEM0CggU2bSh
key:                  extensible-exceptions-0.1.1.4-6aNRrQW8livEM0CggU2bSh
license:              BSD-3-Clause
maintainer:           libraries@haskell.org
synopsis:             Extensible exceptions
description:
    This package provides extensible exceptions for both new and
    old versions of GHC (i.e., < 6.10).

category:             Control
abi:                  84bc7d34028233a22a0efa4576188163
exposed:              True
exposed-modules:      Control.Exception.Extensible
import-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\extensible-exceptions-0.1.1.4-6aNRrQW8livEM0CggU2bSh"

library-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\extensible-exceptions-0.1.1.4-6aNRrQW8livEM0CggU2bSh"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\extensible-exceptions-0.1.1.4-6aNRrQW8livEM0CggU2bSh"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\share\\x86_64-windows-ghc-9.8.4\\extensible-exceptions-0.1.1.4"

hs-libraries:         HSextensible-exceptions-0.1.1.4-6aNRrQW8livEM0CggU2bSh
include-dirs:
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include

depends:              base-4.19.2.0-943b
haddock-interfaces:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\doc\\extensible-exceptions-0.1.1.4\\extensible-exceptions.haddock"

haddock-html:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\doc\\extensible-exceptions-0.1.1.4"
