name:                 hostname
version:              1.0
visibility:           public
id:                   hostname-1.0-FvOCOhmoeqpE2XTuxwUw5c
key:                  hostname-1.0-FvOCOhmoeqpE2XTuxwUw5c
license:              BSD-3-Clause
maintainer:           Max Bolingbroke <batterseapower@hotmail.com>
author:               Max Bolingbroke <batterseapower@hotmail.com>
synopsis:
    A very simple package providing a cross-platform means of determining the hostname

category:             Network
abi:                  61ebe01f7bc8b84d0a4ebb99e0b2a269
exposed:              True
exposed-modules:      Network.HostName
import-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\hostname-1.0-FvOCOhmoeqpE2XTuxwUw5c"

library-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\hostname-1.0-FvOCOhmoeqpE2XTuxwUw5c"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\hostname-1.0-FvOCOhmoeqpE2XTuxwUw5c"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\share\\x86_64-windows-ghc-9.8.4\\hostname-1.0"

hs-libraries:         HShostname-1.0-FvOCOhmoeqpE2XTuxwUw5c
extra-libraries:      kernel32
include-dirs:
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include

depends:              Win32-2.13.4.0-9aa2 base-4.19.2.0-943b
haddock-interfaces:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\doc\\hostname-1.0\\hostname.haddock"

haddock-html:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\doc\\hostname-1.0"
