name:                 old-locale
version:              1.0.0.7
visibility:           public
id:                   old-locale-1.0.0.7-3o8f5tIk0y9DmQiLuISqIJ
key:                  old-locale-1.0.0.7-3o8f5tIk0y9DmQiLuISqIJ
license:              BSD-3-Clause
maintainer:           libraries@haskell.org
synopsis:             locale library
description:
    This package provides the ability to adapt to
    locale conventions such as date and time formats.

category:             System
abi:                  0c9e5d099f9d00a97f3b37754d8d0927
exposed:              True
exposed-modules:      System.Locale
import-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\old-locale-1.0.0.7-3o8f5tIk0y9DmQiLuISqIJ"

library-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\old-locale-1.0.0.7-3o8f5tIk0y9DmQiLuISqIJ"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\old-locale-1.0.0.7-3o8f5tIk0y9DmQiLuISqIJ"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\share\\x86_64-windows-ghc-9.8.4\\old-locale-1.0.0.7"

hs-libraries:         HSold-locale-1.0.0.7-3o8f5tIk0y9DmQiLuISqIJ
include-dirs:
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include

depends:              base-4.19.2.0-943b
haddock-interfaces:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\doc\\old-locale-1.0.0.7\\old-locale.haddock"

haddock-html:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\doc\\old-locale-1.0.0.7"
