name:                 prettyprinter-ansi-terminal
version:              1.1.3
visibility:           public
id:                   prettyprinter-ansi-terminal-1.1.3-49yyYGZmhEjEKfd42COOwH
key:                  prettyprinter-ansi-terminal-1.1.3-49yyYGZmhEjEKfd42COOwH
license:              BSD-2-Clause
maintainer:
    Simon Jakobi <simon.jakobi@gmail.com>, David Luposchainsky <dluposchainsky at google>

author:               David Luposchainsky
homepage:             http://github.com/quchen/prettyprinter
synopsis:             ANSI terminal backend for the »prettyprinter« package.
description:          See README.md
category:             User Interfaces, Text
abi:                  d915f4c4e8d29eb9ae1b16679fc2a881
exposed:              True
exposed-modules:
    Data.Text.Prettyprint.Doc.Render.Terminal
    Data.Text.Prettyprint.Doc.Render.Terminal.Internal
    Prettyprinter.Render.Terminal
    Prettyprinter.Render.Terminal.Internal

import-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\prettyprinter-ansi-terminal-1.1.3-49yyYGZmhEjEKfd42COOwH"

library-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\prettyprinter-ansi-terminal-1.1.3-49yyYGZmhEjEKfd42COOwH"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\prettyprinter-ansi-terminal-1.1.3-49yyYGZmhEjEKfd42COOwH"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\share\\x86_64-windows-ghc-9.8.4\\prettyprinter-ansi-terminal-1.1.3"

hs-libraries:         HSprettyprinter-ansi-terminal-1.1.3-49yyYGZmhEjEKfd42COOwH
include-dirs:
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include

depends:
    ansi-terminal-1.1.3-LoIQLCIYZbkE5HK464mwGd base-4.19.2.0-943b
    prettyprinter-1.7.1-FuC1IVzqwq2GbeVQZWOaln text-2.1.1-3967

haddock-interfaces:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\doc\\prettyprinter-ansi-terminal-1.1.3\\prettyprinter-ansi-terminal.haddock"

haddock-html:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\doc\\prettyprinter-ansi-terminal-1.1.3"
