name:                 prettyprinter-compat-ansi-wl-pprint
version:              1.0.2
visibility:           public
id:
    prettyprinter-compat-ansi-wl-pprint-1.0.2-1AfhEzoGmEE4Q4ya4nyvRn

key:
    prettyprinter-compat-ansi-wl-pprint-1.0.2-1AfhEzoGmEE4Q4ya4nyvRn

license:              BSD-2-Clause
maintainer:           David Luposchainsky <dluposchainsky at google>
author:               David Luposchainsky
homepage:             http://github.com/quchen/prettyprinter
synopsis:
    Drop-in compatibility package to migrate from »ansi-wl-pprint« to »prettyprinter«.

description:          See README.md
category:             User Interfaces, Text
abi:                  8bb4bb6a8ded6ec6807f1669da18da3a
exposed:              True
exposed-modules:      Text.PrettyPrint.ANSI.Leijen
import-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\prettyprinter-compat-ansi-wl-pprint-1.0.2-1AfhEzoGmEE4Q4ya4nyvRn"

library-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\prettyprinter-compat-ansi-wl-pprint-1.0.2-1AfhEzoGmEE4Q4ya4nyvRn"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\prettyprinter-compat-ansi-wl-pprint-1.0.2-1AfhEzoGmEE4Q4ya4nyvRn"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\share\\x86_64-windows-ghc-9.8.4\\prettyprinter-compat-ansi-wl-pprint-1.0.2"

hs-libraries:
    HSprettyprinter-compat-ansi-wl-pprint-1.0.2-1AfhEzoGmEE4Q4ya4nyvRn

include-dirs:
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include

depends:
    base-4.19.2.0-943b prettyprinter-1.7.1-FuC1IVzqwq2GbeVQZWOaln
    prettyprinter-ansi-terminal-1.1.3-49yyYGZmhEjEKfd42COOwH
    text-2.1.1-3967

haddock-interfaces:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\doc\\prettyprinter-compat-ansi-wl-pprint-1.0.2\\prettyprinter-compat-ansi-wl-pprint.haddock"

haddock-html:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\doc\\prettyprinter-compat-ansi-wl-pprint-1.0.2"
