name:                 regex-posix-clib
version:              2.7
visibility:           public
id:                   regex-posix-clib-2.7-BIn2p7YA1ysGGHW5DIIlXY
key:                  regex-posix-clib-2.7-BIn2p7YA1ysGGHW5DIIlXY
license:              LGPL-2.1-only
maintainer:           hvr@gnu.org
synopsis:             "Regex for Windows" C library
description:
    This CABAL package provides the <http://gnuwin32.sourceforge.net/packages/regex.htm Regex for Windows> C library for convenience on operating systems lacking a <https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/regex.h.html POSIX.2 regex> implementation.

category:             Text
abi:                  22a2dd524ce68dd43407f216c921690e
exposed:              True
library-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\regex-posix-clib-2.7-BIn2p7YA1ysGGHW5DIIlXY"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\regex-posix-clib-2.7-BIn2p7YA1ysGGHW5DIIlXY"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\share\\x86_64-windows-ghc-9.8.4\\regex-posix-clib-2.7"

hs-libraries:         HSregex-posix-clib-2.7-BIn2p7YA1ysGGHW5DIIlXY
include-dirs:
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\regex-posix-clib-2.7-BIn2p7YA1ysGGHW5DIIlXY\\include"

haddock-interfaces:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\doc\\regex-posix-clib-2.7\\regex-posix-clib.haddock"

haddock-html:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\doc\\regex-posix-clib-2.7"
