name:                 test-framework-quickcheck2
version:              0.3.0.6
visibility:           public
id:                   test-framework-quickcheck2-0.3.0.6-BAb6CCseiHXEfv6h9JDXqT
key:                  test-framework-quickcheck2-0.3.0.6-BAb6CCseiHXEfv6h9JDXqT
license:              BSD-3-Clause
maintainer:           Andreas Abel
author:               Max Bolingbroke <batterseapower@hotmail.com>
homepage:             https://github.com/haskell/test-framework#readme
synopsis:             QuickCheck-2 support for the test-framework package.
description:
    Allows @QuickCheck-2@ properties to be used with the </package/test-framework test-framework package>.

category:             Testing
abi:                  8a06086f932ecdc4997ca577ea553672
exposed:              True
exposed-modules:      Test.Framework.Providers.QuickCheck2
import-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\test-framework-quickcheck2-0.3.0.6-BAb6CCseiHXEfv6h9JDXqT"

library-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\test-framework-quickcheck2-0.3.0.6-BAb6CCseiHXEfv6h9JDXqT"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4\\test-framework-quickcheck2-0.3.0.6-BAb6CCseiHXEfv6h9JDXqT"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\lib\\x86_64-windows-ghc-9.8.4"
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\share\\x86_64-windows-ghc-9.8.4\\test-framework-quickcheck2-0.3.0.6"

hs-libraries:         HStest-framework-quickcheck2-0.3.0.6-BAb6CCseiHXEfv6h9JDXqT
include-dirs:
    C:\Users\rannr\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include

depends:
    QuickCheck-2.14.3-I1FhA722lgvIMLDoUAnepC base-4.19.2.0-943b
    extensible-exceptions-0.1.1.4-6aNRrQW8livEM0CggU2bSh
    random-1.2.1.3-CD0jthcsdqS3KzMffTC4Rh
    test-framework-0.8.2.2-CNjLaaWipB16eOHWnUyJI4

haddock-interfaces:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\doc\\test-framework-quickcheck2-0.3.0.6\\test-framework-quickcheck2.haddock"

haddock-html:
    "C:\\Users\\rannr\\CS 421\\cs421-mp2\\cs421-release\\mp3-cps\\.stack-root\\snapshots\\aff6004d\\doc\\test-framework-quickcheck2-0.3.0.6"
